version: '3.8'

services:
  sendxpress:
    build: .
    container_name: sendxpress-local
    ports:
      - "8080:80"
    environment:
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - XPRESS_API_USERNAME=${XPRESS_API_USERNAME}
      - XPRESS_API_PASSWORD=${XPRESS_API_PASSWORD}
      - REVOLUT_API_KEY=${REVOLUT_API_KEY:-YOUR_REVOLUT_MERCHANT_API_KEY}
      - REVOLUT_WEBHOOK_SECRET=${REVOLUT_WEBHOOK_SECRET:-YOUR_WEBHOOK_SECRET}
      - REVOLUT_PUBLIC_KEY=${REVOLUT_PUBLIC_KEY:-YOUR_REVOLUT_PUBLIC_KEY}
      - REVOLUT_ENVIRONMENT=${REVOLUT_ENVIRONMENT:-sandbox}
    env_file:
      - .env.local
    volumes:
      # Mount for development (hot reload)
      - ./src:/usr/share/nginx/html/src:ro
      - ./index-modular.html:/usr/share/nginx/html/index.html:ro
    networks:
      - sendxpress-network

networks:
  sendxpress-network:
    driver: bridge
